### ISSUE TITLE
Error on addon not working any more

### ISSUE THREAD

**Issue by ustunsoz** [dy1io/hassio-addons#12]
I know you have depreciated the addon, but I am writing maybe you can recover with a small tweak.

The ngrok client addon log gives following error:
s6-overlay-suexec: fatal: can only run as pid 1

and not working anymore

I will be grateful if you can handle it.

**Comment by ustunsoz** [comment]
https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

according to direction above, github files permissions should be updated???

**Comment by dy1io** [comment]
I just pushed 2.1.8 which should resolve that issue.

**Comment by ustunsoz** [comment]
works well I appreciate your effort and prompt reply, thanks

**Comment by zlucio** [comment]
I can't update to version 2.1.8 [ngrok client 2.1.6 installed on Hassio which works fine] I have this error

 Error updating ngrok Client: Can't install 1ded40ef/amd64-addon-ngrok:2.1.8: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.1.8&fromImage=1ded40ef%2Famd64-addon-ngrok&platform=linux%2Famd64: Not Found ("pull access denied for 1ded40ef/amd64-addon-ngrok, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

TNX

**Comment by zlucio** [comment]
Nothing works anymore .... Home Assistant has disabled everything ... Even restoring the old configurations does not allow any functionality ... Was it bothering?!?!
