### ISSUE TITLE
Getting error after update

### ISSUE THREAD

**Issue by sheminasalam** [dy1io/hassio-addons#14]
I am getting the following error after upgrade.

`
Missing option 'auth' in tunnels in ngrok Client (fdfb012e_ngrok).
`
How to sort this?

**Comment by fixsssator** [comment]
Hi @sheminasalam you should add the line 

auth: ""

**Comment by sheminasalam** [comment]
That solved it, hope it gets updated in docs

**Comment by aasimenator** [comment]
Thank you!

**Comment by Quarks2021** [comment]
Thank you very much!

**Comment by fixsssator** [comment]
Glad to help everyone :)
