### ISSUE TITLE
Auth required

### ISSUE THREAD

**Issue by Zewe77** [dy1io/hassio-addons#15]
I know its deprecated but after the last update, I needed to add the "Auth:" to the config to make it work, this makes it so that you have a login when you open the web or app. in the web it works but not the app. hoping maybe someone can have a look at this cause I have no clue....

**Comment by Zewe77** [comment]
Any one have the same issue or working for everyone else?
I can use the webpage with the Ngrok tunnel just have to logon with the username/password
If i try and use the app i get a popup for username password but after just the same error as when its wrong address, i can provide a log if that helps...

**Comment by fixsssator** [comment]
Hi @Zewe77  try like this:  
auth: "" 
- you have to add an empty quotes

**Comment by Zewe77** [comment]
> Hi @Zewe77 try like this: auth: ""
> 
> * you have to add an empty quotes

thank you this solved it, I think I have tried everything except this, sometimes I'm an idiot :D
