### ISSUE TITLE
Addons can't create the tunnel after startup

### ISSUE THREAD

**Issue by dbarvik** [dy1io/hassio-addons#17]
Hello,
I am using Home assistant version 2022.8.1 with supervisor 2022.08.3 on RPI 4 in docker. Addon works normally, but after reboot the addon won't create a tunnel and in log shows this error.

_[14:19:49] INFO: Starting ngrok...
NAME:
   start - start tunnels by name from the configuration file
USAGE:
   ngrok start [command options] [arguments...]
DESCRIPTION:
   Starts tunnels by name from the configuration file. You may specify any
   number of tunnel names. You may start all tunnels in the configuration
   file with the --all switch.
EXAMPLES:
   ngrok start dev        # start tunnel named 'dev' in the configuration file
   ngrok start web blog   # start tunnels named 'web' and 'blog'
   ngrok start --all      # start all tunnels defined in the config file
OPTIONS:
   --all		start all tunnels in the configuration file
   --authtoken 		ngrok.com authtoken identifying a user
   --config		path to config files; they are merged if multiple
   --log "false"	path to log file, 'stdout', 'stderr' or 'false'
   --log-format "term"	log record format: 'term', 'logfmt', 'json'
   --log-level "info"	logging level
   --none		start running no tunnels
   --region 		ngrok server region [us, eu, au, ap, sa, jp, in] (default: us)
ERROR:  Your configuration file must define at least one tunnel when using --all. To intentionally start no tunnels, use ngrok start --none.
jq: error (at <stdin>:1): null (null) has no keys_

In addon page I have ticked the automatic start after boot and watchdog. But I am getting the same error repeatedely. In config I have all the tunnel information. 

After clicking on Restart addon, it works normaly. 
I am facing this problem after update from Hassio 2022.4.1 to 2022.8.1. I tried to downgrade to 2022.4.1 but it still has the same problem.

Is it possible to add the fix for restart of the addon, or something different? When I am away from my home a need to connect to my local network to manually restart the addons a then it works.

And in the error message is shown the missing config file, but when I open look into container with this addon, I can see my config file. Also I can see the config in config page of addon.

**Comment by dy1io** [comment]
Are you running the full HA OS or just a supervised instance? I've never tested it on anything other than the full HA OS and being that I've deprecated the add-on I don't ever intend to add support/test for it.
 
If you haven't already it might be worth running a rebuild on the add-on, that will update the ngrok client. I did install it and was able to reboot my host without seeing the error you got so hopefully a simple rebuild fixes it.
