### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by 7usher7** [dy1io/hassio-addons#9]
When I launch the addon, I get the following message in the console

`s6-overlay-suexec: fatal: can only run as pid 1`

It doesn't work. How do I fix this?

**Comment by 7usher7** [comment]
I added a line to the configuration file and it worked
`"init": false,`

**Comment by ustunsoz** [comment]
COuld you please eloborate where to add the script I am on HasOS raspberry pi and using as addon 

the following change on addon configuration did not workout:
- name: hass
  proto: http
  addr: 8123
  inspect: false
  init: false

**Comment by ustunsoz** [comment]
> I added a line to the configuration file and it worked `"init": false,`

COuld you please eloborate where to add the script I am on HasOS raspberry pi and using as addon

the following change on addon configuration did not workout:

name: hass
proto: http
addr: 8123
inspect: false
init: false
